export const DOC_SIGNATURES_ACTION_TYPES = {
  DOC_SIGNATURES_INIT: "docSignature/DOC_SIGNATURES_INIT",
  SET_DOC_SIGNATURES: "docSignature/SET_DOC_SIGNATURES",
  REMOVE_SIGNATURE_FROM_DOC: "docSignature/REMOVE_SIGNATURE_FROM_DOC",
  SET_SIGNATURE_IS_SAVED: "docSignature/SET_SIGNATURE_IS_SAVED",
  CREATE_DOC_SIGNATURES: "docSignature/CREATE_DOC_SIGNATURES",
  FETCH_SIGNATURES_START: "docSignature/FETCH_SIGNATURES_START",
  FETCH_SIGNATURES_SUCCESS: "docSignature/FETCH_SIGNATURES_SUCCESS",
  FETCH_SIGNATURES_FAILED: "docSignature/FETCH_SIGNATURES_FAILED",
};
